# SwiftLint configuration file for root directory
# Find all the available rules by running:
# swiftlint rules

# Rules that are disabled
disabled_rules:
  - file_header # Disable file headers
  - explicit_type_interface # Disabled: makes code too verbose and harder to review
  - implicitly_unwrapped_optional # Disabled: common pattern in XCTest setup methods
  - type_body_length # Disabled: test files often exceed 300 lines
  - multiple_closures_with_trailing_closure # Disabled: SwiftUI patterns often use this

opt_in_rules:
  - multiline_parameters # Each parameter on a different line
  - multiline_arguments # Each argument on a different line
  - vertical_parameter_alignment_on_call # Vertical alignment of parameters
  # Code Quality
  - explicit_init # Explicitly calling .init() should be avoided
  - redundant_type_annotation # Variables should not have redundant type annotation
  - closure_spacing # Closure expressions should have a single space inside each brace
  - operator_usage_whitespace # Operators should be surrounded by a single whitespace
  - number_separator # Underscores should be used as thousand separator in large numbers
  - sorted_imports # Imports should be sorted alphabetically
  # Best Practices
  - force_unwrapping # Force unwrapping should be avoided
  - implicitly_unwrapped_optional # Implicitly unwrapped optionals should be avoided when possible
  - fatal_error_message # A fatalError call should have a message
  - fallthrough # Fallthrough should be avoided
  - empty_count # Prefer checking isEmpty over comparing count to zero
  - first_where # Prefer using .first(where:) over .filter { }.first
  - contains_over_first_not_nil # Prefer contains over first(where:) != nil
  - last_where # Prefer using .last(where:) over .filter { }.last
  # Documentation
  - missing_docs # Public declarations should be documented
  # Naming
  - identifier_name # Identifier names should follow conventions
  - type_name # Type name should only contain alphanumeric characters
  # Code Organization
  - vertical_whitespace_closing_braces # Don't include vertical whitespace before closing braces
  - vertical_whitespace_opening_braces # Don't include vertical whitespace after opening braces
  - empty_string # Prefer using isEmpty over comparing string to an empty string literal
  # Modern Swift
  - toggle_bool # Prefer toggle() instead of someBoolean = !someBoolean
  - contains_over_filter_count # Prefer contains over using filter(where:).count > 0
  - contains_over_filter_is_empty # Prefer contains over using filter(where:).isEmpty

included:
  - TelnyxVoiceAIWidget/TelnyxVoiceAIWidget
  - TelnyxVoiceAIWidget/TelnyxVoiceAIWidgetTests
  - SampleApp/SampleApp
  - SampleApp/SampleAppTests
  - SampleApp/SampleAppUITests

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - build
  - dist
  - reports
  - TelnyxVoiceAIWidget/TelnyxVoiceAIWidget/TelnyxVoiceAIWidget.docc

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length:
  warning: 250
  error: 400

file_length:
  warning: 1000
  error: 1500

# Documentation requirements for public APIs
missing_docs:
  warning: open # Warn on open/public declarations without documentation
  excludes_extensions: false
  excludes_inherited_types: false

# reporter type (xcode, json, csv, checkstyle)
reporter: "xcode"
